apiVersion: v1
kind: Service
metadata:
  name: desafio-devops 
  namespace: desafio-devops
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: ui 
    port: 8089
    protocol: TCP
    targetPort: 3000
  selector:
    component: desafio-devops 
  type: ClusterIP
