node {
    try {
        def BRANCH_NAME = "development"
        def IMAGE_VERSION = "v-$BUILD_NUMBER"
        def REPO_GIT = "https://github.com/richardsonlima/desafios-devops.git"
        def REGISTRY_REPO = "richardsonlima/desafio-devops"

        stage("cloning_project") {
                checkout([$class: 'GitSCM',
                    userRemoteConfigs: [[url: "$REPO_GIT"]],
                    branches: [[name: "$BRANCH_NAME"]],
                    credentialsId: '',
                    clean: false,
                    extensions: [[$class: 'SubmoduleOption',
                                    disableSubmodules: false,
                                    parentCredentials: false,
                                    recursiveSubmodules: true,
                                    reference: '',
                                    trackingSubmodules: false]],
                    doGenerateSubmoduleConfigurations: false,
                    submoduleCfg: []
                ])
        }

        stage('container_up') {
            dir(env.WORKSPACE) {
                sh(script: "pwd")
                sh(script: "docker-compose -f kubernetes/docker-compose.yaml up --build -d")
            }
        }

        stage('container_stop') {
            dir(env.WORKSPACE) {
                sh """
                    for services in `docker-compose -f kubernetes/docker-compose.yaml config --services`; do
                        docker-compose -f kubernetes/docker-compose.yaml stop -t1 \$services
                    done
                """
            }
        } 

        stage('push_container_to_registry') {
            dir(env.WORKSPACE) {
                sh """
                    pwd
                    docker build -t $REGISTRY_REPO:$IMAGE_VERSION -f kubernetes/Dockerfile .
                    docker push $REGISTRY_REPO:$IMAGE_VERSION
                """
            }
        }

        stage('push_container_to_registry') {
            dir(env.WORKSPACE) {
                sh """
                    cd kubernetes
                    /usr/local/bin/helm install --namespace=desafio-devops ./kubernetes/helm
                """
            }
        }
        
    } catch (error) {
        currentBuild.result = 'FAILURE'
        throw error
    } finally {
        echo "RESULT: ${currentBuild.result}"
    }    
}
